name: Build all platforms

# Don't trigger to changing READMEs and such
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-win32:
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - msvc
          # TODO
          #- clang
        mode:
          - debug
          - release

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSVC
        # This seems to not be maintained anymore, so fork it and update e.g. node version?
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: x64

      - name: Get toolset info
        # TODO -v for clang
        run: |
          "${{ matrix.compiler }}"

      - name: Build Win32
        shell: cmd
        # TODO: passing matrix.compiler currently does nothing
        run: |
          scripts\build.bat "${{ matrix.compiler }}" "${{ matrix.mode }}"

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
        compiler:
          - clang
          #- gcc TODO
        mode:
          - debug
          - release

    steps:
      - uses: actions/checkout@v6

      # Have to apt-get update to find SDL2
      - name: Update APT package index
        run: |
          sudo apt-get update

      - name: Install SDL2
        run: |
          sudo apt-get install -y build-essential clang libsdl2-dev

      - name: Get toolset info
        run: |
          "${{ matrix.compiler }}" -v

      - name: Build Linux
        run: |
          chmod +x ./scripts/build.sh
          time ./scripts/build.sh "${{ matrix.platform }}" "${{ matrix.compiler }}" "${{ matrix.mode }}"

  build-macos:
    # See if we can do "macos-latest-large" without a paid Github version -> can not
    runs-on: macos-15-intel
    strategy:
      fail-fast: false
      matrix:
        platform:
          - mac
        compiler:
          - clang
        mode:
          - debug
          - release

    steps:
      - uses: actions/checkout@v6

      - name: Untap aws/tap
        run: |
          brew untap aws/tap

      - name: Install SDL2
        run: |
          brew install sdl2

      - name: Get toolset info
        run: |
          "${{ matrix.compiler }}" -v

      - name: Build macOS
        # actions said to untap aws/tap
        run: |
          chmod +x ./scripts/build.sh
          time ./scripts/build.sh "${{ matrix.platform }}" "${{ matrix.compiler }}" "${{ matrix.mode }}"

# https://github.com/emscripten-core/setup-emsdk
  build-web:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - web
        compiler:
          - emcc
        mode:
          - debug
          - release

    steps:
      - uses: actions/checkout@v6

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v15
        with:
        # Or latest
          version: 6.0.1

      - name: Get toolset info
        run: |
          "${{ matrix.compiler }}" -v

      - name: Build Web
        run: |
          chmod +x ./scripts/build.sh
          time ./scripts/build.sh "${{ matrix.platform }}" "${{ matrix.compiler }}" "${{ matrix.mode }}"
